# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.cache/wt} [current_project]
set_property parent.project_path {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {{D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/imstruction.mem}}
read_verilog -library xil_defaultlib {
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/ALU.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/Data_Mem.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/InstrFetch.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/InstrMem.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/PCAdder.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/PCTarget.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/ProgramCounter.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/RegFile.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/SignExtend.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/controller.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/forward1_mux.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/forward2_mux.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/hazard_unit.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/muxPC.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/mux_execute.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/mux_wb.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/register_decode_execute.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/register_execute_mem.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/register_fetch.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/register_mem_wb.v}
  {D:/RV32I-Pipelined-processor/Pipelined Processor/Pipelined Processor.srcs/sources_1/new/main.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
